# Generated by Django 2.1 on 2018-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180828_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='body',
            new_name='details',
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=250),
        ),
    ]
